### PR TITLE
Update Readme.md with Github discussions link

### PR DESCRIPTION
**Pull request by mohanhbk**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by nils-a — CHANGES_REQUESTED** [review]
@mohanhbk Thanks for your contribution.

Could you move the **Discussion** section above **Licencse**, please?

**Review by augustoproiete — CHANGES_REQUESTED** [review]
Looks good. Let's just move this section to be after "Aliases" and before the "Apache License 2.0" to more or less match the flow we're using in other repos e.g. `Usage -> Discussion -> (...) -> License`

**Comment by mohanhbk** [comment]
@augustoproiete @nils-a Done as per your comments

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by nils-a** [comment]
@mohanhbk your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
